config/routes.rb
Rails.application.routes.draw do
  get 'attend/new'
  get 'attend/delete'
  get 'attend/index'
  get 'attend/create'

  resources :events
  resources :hikes
  get 'social/social_list'

  resources :users
  get "sign up" => "users#new", :as => "sign_up"
  resources :sessions
  root 'welcome#index'
  resources :microposts,          only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  attr_accessor :password

  email_regex = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username,  :presence => true,
            :length               => { :maximum => 50}
  validates :email,     :presence => true,
            :format               => { :with => email_regex},
            :uniqueness           => { :case_sensitive => false}
  validates :password,    :confirmation => true,
            :presence             => true,
            :length               => { :within => 6..40}
  before_save :encrypt_password
  def has_password?(submitted_password)
    encrypted_password==encrypt(submitted_password)
  end
  def self.authenticate(email, submitted_password)
    user = self.find_by email: email
    if user && user.encrypted_password == Digest::SHA2.hexdigest("#{user.salt}--#{submitted_password}")
      user
    else
      nil
    end
  end

  private
    def encrypt_password
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  layout "application"
  layout "login-signup", :only => [:new, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
    @hike = Hike.all
    @event = Event.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @user=User.find(params[:id])
      @microposts = @user.microposts.paginate(page: params[:page])
      @weather_lookup = WeatherLookup.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<provide(:title, "Edit Existing Users")>
<h1>Editing User</h1>
<div class="center">		

	<%= render 'form' %>

</div>

app/views/users/index.html.erb
  <provide(:title, "List of Users")>
<div id="header">
  <h1 id="logotype">SLOG</h1>
</div>


<%= will_paginate %>

<ul class="users">
<% @users.each do |user| %>
  <li>
    <%= link_to user.name, user %>
  </li>
<% end %>
</ul>
<%= will_paginate %>




<!--
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

app/views/users/new.html.erb
<provide(:title, "Become a SLOG and start planning hikes easily now!")>
<div id="login-center">
	<h1>Create Your Account</h1>
		<div class="form-space">
			<div class="forms">
				<%= simple_form_for (@user) do |f| %>
				  <%= f.input :username %> </br>
				  <%= f.input :email %> </br>
				  <%= f.input :password %> </br>
				  <%= f.input :password_confirmation %> </br>
				  <%= f.button :submit %>
				<% end %>
			</div>
		</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "SLOG Home Panel") %>
<div id="user-home-panel">
	<p id="notice"><%= notice %></p>
	<div class="column-3" id="user-info">
		<h2><%= @user.username %></h2>
		<%= image_tag("profile_placeholder.png") %>
		</br>
		<p>Region: Vancouver </p>
		<p>Hikes Done: 7</p>

		</br>
		<h3>Current Weather</h3>
		<p>It is <%= to_celcius(@weather_lookup.temperature) %>°C degrees in Vancouver, BC!</p>
		<%= image_tag @weather_lookup.icon %>
		<div id="upcoming-events">
			<h3>Upcoming Events</h3>
			<div class="event-item">
				<h4><%= link_to "TGIF", controller: :events, action: :index %></h4>
				<p class="time-stamp">2015 November 5</p>
				<p>Where: Elk Mountain</p>
			</div>
			<div class="event-item">
				<h4><%= link_to "Weekend Hike", controller: :events, action: :index %></h4>
				<p class="time-stamp">2015 December 15</p>
				<p>Where: Elephant Lake</p>
			</div>
		</div>
	</div>

	<div class="column-2-3" >
		<h3>Your Hikes</h3>
		<div id="user-map-container" >
			<div id="user-map-canvas"></div>
		</div>
		</br></br>
		</br>

		<div class="feed-item">
	 	<% if @user.microposts.any? %>
		 <h3>BLOG: (<%= @user.microposts.count %>)</h3>
		 <ol class="microposts">
			 <%= render @microposts %>
		 </ol>
		 <%= will_paginate @microposts %>
	 	<% end %>
	 	</br></br></br>
		<% if current_user?(User.find(params[:id])) %>
  		<div class="row">
    		<aside class="col-md-4">
<!--       		<section class="user_info">
						<h1><%= current_user.username %></h1>
							<span><%= link_to "view my profile", current_user %></span>
							<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
      		</section> -->
      		<h3>Update</h3>
      		<section class="micropost_form">
						<%= simple_form_for(:micropost, :url =>microposts_path)  do |f| %>
  						<div class="field">
    						<%= f.input :content, as: :text, :label => "Your Comment" %>
  						</div>
  						</br>
  						<%= f.button :submit, "Post" %>
						<% end %>
      		</section>
    		</aside>
  		</div>
			<% end %>
 		</div>
	</div>
<!-- 	<div class="column-3" id="user-feed">
		<div class="feed-item">
			<h4>Hey there I am a feed.</h4>
			<p>Some feed goes here. I am not sure what will go here right now. Sample text will be the same for each user?</p>
			<p class="time-stamp">2015 Novemeber 5 | </p>
		</div>
		<div class="feed-item">
			<h4>I am another feed item.</h4>
			<p>Perhaps upcoming events? Public events? New hikes that have been added to the archive?</p>
			<p class="time-stamp">2015 Novemeber 5 | </p>
		</div>
	</div>

	<div class="column-3" id="user-options">
		<ul id="user-buttons">
			<li><h2><%= link_to 'View Hikes', :controller => :hikes, :action => :index   %></h2></li>
			<li><h2><%= link_to 'Events', :controller => :events, :action => :index    %></h2></li>
			<li><h2><%= link_to 'Forums', user_path %></h2></li>
			<li><h2><%= link_to 'Groups', user_path %></h2></li>
		</ul>
	</div> -->

</div>