config/routes.rb
Rails.application.routes.draw do
  get 'attend/new'
  get 'attend/delete'
  get 'attend/index'
  get 'attend/create'

  resources :events
  resources :hikes
  get 'social/social_list'

  resources :users
  get "sign up" => "users#new", :as => "sign_up"
  resources :sessions
  root 'welcome#index'
  resources :microposts,          only: [:create, :destroy]

end

app/models/hike.rb
class Hike < ActiveRecord::Base
  has_many :events, :dependent => :destroy
  
  validates :name, presence: true, uniqueness: true
  validates :region, presence: true
  validates :distance, presence: true
  validates :distance, :numericality => { :less_than_or_equal_to => 50000 }
  validates :distance, :numericality => { :greater_than_or_equal_to => 0 }
  validates :lat, presence: true
  validates :lat, :numericality => { :greater_than_or_equal_to => -90 }
  validates :lat, :numericality => { :less_than_or_equal_to => 90 }
  validates :lng, presence: true
  validates :lng, :numericality => { :greater_than_or_equal_to => -180 }
  validates :lng, :numericality => { :less_than_or_equal_to => 180 }
  
  #Attempt to add coord params to default root
  #def to_param
  #  id.to_s+"?lat="+lat.to_s+"&lng="+lng.to_s;
  #end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :set_hike, only: [:show, :edit, :update, :destroy]

  # GET /hikes
  # GET /hikes.json
  def index
    @hikes = Hike.all
  end

  # GET /hikes/1
  # GET /hikes/1.json
  def show
  end

  # GET /hikes/new
  def new
    @hike = Hike.new
  end

  # GET /hikes/1/edit
  def edit
  end

  # POST /hikes
  # POST /hikes.json
  def create
    @hike = Hike.new(hike_params)

    respond_to do |format|
      if @hike.save
        format.html { redirect_to @hike, notice: 'Hike was successfully created.' }
        format.json { render :show, status: :created, location: @hike }
      else
        format.html { render :new }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hikes/1
  # PATCH/PUT /hikes/1.json
  def update
    respond_to do |format|
      if @hike.update(hike_params)
        format.html { redirect_to @hike, notice: 'Hike was successfully updated.' }
        format.json { render :show, status: :ok, location: @hike }
      else
        format.html { render :edit }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hikes/1
  # DELETE /hikes/1.json
  def destroy
    @hike.destroy
    respond_to do |format|
      format.html { redirect_to hikes_url, notice: 'Hike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hike
      @hike = Hike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hike_params
      params.require(:hike).permit(:name, :region, :distance, :difficulty, 
      :grade, :open_date,:close_date)
    end
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/views/hikes/_form.html.erb
<div class="center">
		<div class="form-space">
			<div class="form-container">
				<%= simple_form_for (@hike) do |f| %>
				<%= f.input :name %> </br>
				<%= f.input :region %> </br>
				<%= f.input :distance %> </br>
				<%= f.input :difficulty %> </br>
				<%= f.input :grade %> </br>
				<%= f.input :open_date %> </br>
				<%= f.input :close_date %> </br>
				<%= f.button :submit %>
				<% end %>
			</div>
		</div>
</div>

app/views/hikes/edit.html.erb
<h1>Editing Hike</h1>

<%= render 'form' %>

<%= link_to 'Show', @hike %> |
<%= link_to 'Back', hikes_path %>

app/views/hikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hikes</h1>
<div class="center">
  <table id="hike_list">
    <thead>
      <tr>
        <th>Name of Hike</th>
        <th>Distance</th>
        <th>Region</th>
        <th>Difficulty</th>
        <th>Ratings</th>
      </tr>
    </thead>

    <tbody>
      <% @hikes.each do |hike| %>
        <tr>
          <td><%= link_to hike.name, hike_path(hike, :lat => hike.lat, :lng => hike.lng), 'data-no-turbolink' => true %></td>
          <td><%= hike.distance %> km</td>
          <td><%= hike.region %></td>
          <td><%= hike.difficulty %></td>   
          <td><%= hike.rating.presence || 'no rating available' %></td>     
  <!--         <td><%= link_to 'Edit', edit_hike_path(hike) %></td>
          <td><%= link_to 'Destroy', hike, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
  <p><em>Route information courtesy of <%= link_to 'Vancouver Trails', "http://www.vancouvertrails.com/trails/" %></em></p>
</div>
<br>

app/views/hikes/new.html.erb
<h1>New Hike</h1>

<%= render 'form' %>

<%= link_to 'Back', hikes_path %>

app/views/hikes/show.html.erb
<h1><%= @hike.name %> </h1>
<div class="center">
	<div id="hike-banner"></div>
	<div id="hike-map-container" >
		<div id="map-canvas"></div>		
		</br>
	</div>
	<div class="column-2" id="hike-show" >		
		<h2>Region: </h2><p><%= @hike.region %> </p></br>
		<h2>Rating: </h2><p><%= @hike.rating %> </p></br>
		<h2>Difficulty: </h2><p><%= @hike.difficulty %> </p></br>
		<h2>Distance: </h2><p><%= @hike.distance %>km </p></br>		
	</div>
	<div id="hike-info">
		<h3>About <%= @hike.name %></h3>
		<p>
			Description Needed
		</p>
	</div>
</div>