config/routes.rb
Rails.application.routes.draw do
  get 'attend/new'
  get 'attend/delete'
  get 'attend/index'
  get 'attend/create'

  resources :events
  resources :hikes
  get 'social/social_list'

  resources :users
  get "sign up" => "users#new", :as => "sign_up"
  resources :sessions
  root 'welcome#index'
  resources :microposts,          only: [:create, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :hike
  
  validates :hike_id, 	presence: 	true
  validates :location, 	presence: 	true
  validates :name, 		presence: 	true, uniqueness: true  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @weather_lookup = WeatherLookup.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to action: "index", notice: 'Event was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to action: "index", notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 def join
    #  respond_to do |format|
    # @event.update(event.user_participating) 
    #     format.html { redirect_to @event, notice: 'Joined.' }
    #     format.json { render :show, status: :ok, location: @event }
     # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :date, :hike_id, :user_participating)
    end
end

app/helpers/events_helper.rb
module EventsHelper

	def days_left( dateNow, eventDate )
		daysLeft = ( eventDate - dateNow ).to_i
		if daysLeft < 0  
			return "Event has already passed"
		elsif daysLeft == 0 
			return "The event is today!"				
		else
			return "Only " + daysLeft.to_s + " days left until the event!" 
		end
	end 

end

app/views/events/_form.html.erb
<div class="center">
	<div class="form-space">
		<div class="form-container">
			<%= simple_form_for(@event) do |f| %>
			  <%= f.error_notification %>
				    <%= f.input :name %> </br>
				    <%= f.input :location %> </br>
				    <%= f.input :date %> </br>
				    <%= f.label :hike %>
				    <%= collection_select(:event, :hike_id, Hike.all, :id, :name, options = {:prompt => 'Please select a Hike'}) %> </br>
				    </br>
					<%= f.button :submit %>
			<% end %>
		</div>
    </div>
</div>
    

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<div class="centering">
	<%= render 'form' %>
	<%= link_to 'Show', @event %> |
	<%= link_to 'Back', events_path %>
</div>	

app/views/events/index.html.erb
<h1>All SLOG Events</h1>
<div class="center">
  <p id="notice"><%= notice %></p>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>        
        <th>Hike</th>
        <th>Meet Up Location</th>
        <!-- <th>Who is going</th> -->
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr> 
          <td><%=
		  	@hike = Hike.find_by_id(event.hike_id) 
		  	link_to event.name, event_path(event, :lat => @hike.lat, :lng => @hike.lng), 'data-no-turbolink' => true 
		  %></td>
          <td><%= event.date %></td>
          <td> </td>
          <td><%= event.location %></td>
          <!-- <td><%= event.user_participating %></td> -->
          <!-- below should be admin only-->
<!--           <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<div class="center">
	<%= render 'form' %>

	<%= link_to 'Back', events_path %>
	
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<div class="center">
		
	<p id="notice"><%= notice %></p>
	<h3><%= days_left( DateTime.now.to_date, @event.date.to_date ) %> </h3>
	<div class="centering">
		<p> <strong>Date:</strong> <%= @event.date.to_date.to_formatted_s(:long_ordinal) %> </p>
	 	<p> <strong>Time:</strong> <%= @event.date.to_s(:time) %></p>
	 	<p> <strong>Meet up Location:</strong> <%= @event.location %></p>
		<p>
		  <strong>Hike:</strong>	  
		  <%=
		  	@hike = Hike.find_by_id(@event.hike_id) 
		  	link_to @hike.name, hike_path(@event.hike_id, :lat => @hike.lat, :lng => @hike.lng), 'data-no-turbolink' => true 
		  %>
		  <p> <strong>Current Weather: </strong> <%= to_celcius(@weather_lookup.temperature) %> °C at <%= @event.location %></p> 
		</p>
		<div id="event-map-container">
			<div id="map-canvas"></div>
<!-- <br>
<div class="container">
 <h2>Enter Username To Join</h2>
  <form class="form-horizontal" role="form">
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Username:</label>
      <div class="col-sm-10">          
        <input type="name" class="form-control" id="name" placeholder="Enter Username">
      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
</div>
</br> -->

		</div>
		</br></br></br>
		<br>
		<%= link_to 'Attend', attend_index_path %>
		</br><br><br>
		<%= link_to 'Edit', edit_event_path(@event) %> |
		<%= link_to 'Back', events_path %>
	             </br></br>
	</div>
</div>