config/routes.rb
Rails.application.routes.draw do
  get 'attend/new'
  get 'attend/delete'
  get 'attend/index'
  get 'attend/create'

  resources :events
  resources :hikes
  get 'social/social_list'

  resources :users
  get "sign up" => "users#new", :as => "sign_up"
  resources :sessions
  root 'welcome#index'
  resources :microposts,          only: [:create, :destroy]

end

app/models/attend.rb
class Attend < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
	  validates :user_id, presence: true
	  validates :event_id, presence: true

	  has_one :event_id
	  has_one :user_id
end

app/models/bringitem.rb
class Bringitem < ActiveRecord::Base
	belongs_to :bringlist
end

app/models/bringlist.rb
class Bringlist < ActiveRecord::Base
	has_many :bringitems
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :hike
  
  validates :hike_id, 	presence: 	true
  validates :location, 	presence: 	true
  validates :name, 		presence: 	true, uniqueness: true  

end

app/models/hike.rb
class Hike < ActiveRecord::Base
  has_many :events, :dependent => :destroy
  
  validates :name, presence: true, uniqueness: true
  validates :region, presence: true
  validates :distance, presence: true
  validates :distance, :numericality => { :less_than_or_equal_to => 50000 }
  validates :distance, :numericality => { :greater_than_or_equal_to => 0 }
  validates :lat, presence: true
  validates :lat, :numericality => { :greater_than_or_equal_to => -90 }
  validates :lat, :numericality => { :less_than_or_equal_to => 90 }
  validates :lng, presence: true
  validates :lng, :numericality => { :greater_than_or_equal_to => -180 }
  validates :lng, :numericality => { :less_than_or_equal_to => 180 }
  
  #Attempt to add coord params to default root
  #def to_param
  #  id.to_s+"?lat="+lat.to_s+"&lng="+lng.to_s;
  #end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

  private
  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  attr_accessor :password

  email_regex = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username,  :presence => true,
            :length               => { :maximum => 50}
  validates :email,     :presence => true,
            :format               => { :with => email_regex},
            :uniqueness           => { :case_sensitive => false}
  validates :password,    :confirmation => true,
            :presence             => true,
            :length               => { :within => 6..40}
  before_save :encrypt_password
  def has_password?(submitted_password)
    encrypted_password==encrypt(submitted_password)
  end
  def self.authenticate(email, submitted_password)
    user = self.find_by email: email
    if user && user.encrypted_password == Digest::SHA2.hexdigest("#{user.salt}--#{submitted_password}")
      user
    else
      nil
    end
  end

  private
    def encrypt_password
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end
end

app/models/weather_lookup.rb
class WeatherLookup 
	def fetch_weather
    HTTParty.get("http://api.wunderground.com/api/0e7aecad3bdf9da6/hourly/q/Canada/Vancouver.xml")
 	end

 	attr_accessor :temperature, :icon
 	def initialize
  	weather_hash = fetch_weather
  	assign_values(weather_hash)
	end

	def assign_values(weather_hash)
      hourly_forecast_response = weather_hash.parsed_response['response']['hourly_forecast']['forecast'].first
      self.temperature = hourly_forecast_response['temp']['english']
      self.icon = hourly_forecast_response['icon_url']
 	end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :set_hike, only: [:show, :edit, :update, :destroy]

  # GET /hikes
  # GET /hikes.json
  def index
    @hikes = Hike.all
  end

  # GET /hikes/1
  # GET /hikes/1.json
  def show
  end

  # GET /hikes/new
  def new
    @hike = Hike.new
  end

  # GET /hikes/1/edit
  def edit
  end

  # POST /hikes
  # POST /hikes.json
  def create
    @hike = Hike.new(hike_params)

    respond_to do |format|
      if @hike.save
        format.html { redirect_to @hike, notice: 'Hike was successfully created.' }
        format.json { render :show, status: :created, location: @hike }
      else
        format.html { render :new }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hikes/1
  # PATCH/PUT /hikes/1.json
  def update
    respond_to do |format|
      if @hike.update(hike_params)
        format.html { redirect_to @hike, notice: 'Hike was successfully updated.' }
        format.json { render :show, status: :ok, location: @hike }
      else
        format.html { render :edit }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hikes/1
  # DELETE /hikes/1.json
  def destroy
    @hike.destroy
    respond_to do |format|
      format.html { redirect_to hikes_url, notice: 'Hike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hike
      @hike = Hike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hike_params
      params.require(:hike).permit(:name, :region, :distance, :difficulty, 
      :grade, :open_date,:close_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title =  "SLOG - Your one stop place to plan your hiking trip!"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end	
	end
end

app/helpers/attend_helper.rb
module AttendHelper
end

app/helpers/bringlist_helper.rb
module BringlistHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def days_left( dateNow, eventDate )
		daysLeft = ( eventDate - dateNow ).to_i
		if daysLeft < 0  
			return "Event has already passed"
		elsif daysLeft == 0 
			return "The event is today!"				
		else
			return "Only " + daysLeft.to_s + " days left until the event!" 
		end
	end 

end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
      session[:user_id] = user.id
      self.current_user = user
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def signed_in?
        !current_user.nil?
    end

    def sign_out
        session[:user_id] = nil
        self.current_user = nil
    end

    def current_user?(user)
      user == current_user
    end

    def deny_access
      redirect_to signin_path, :notice => "please sign in to access this page."
    end
end

app/helpers/social_helper.rb
module SocialHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def to_celcius( fahrenheit )		
		return number_with_precision( fahrenheit.to_i/32.0, :precision => 2)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= favicon_link_tag 'SLOGo.png'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	<div id="main-nav">
		<ul id="home-nav">
			<li><%= image_tag("SLOGo.png") %></li>
			<% if current_user %>
				<li><h3><%= link_to 'SLOG', current_user %></h3> </li> |
				<li><%= link_to 'Home', current_user, 'data-no-turbolink' => true %></li> |		
				<li><%= link_to 'View Hikes', :controller => :hikes, :action => :index   %></li> |
				<li><%= link_to 'Events', :controller => :events, :action => :index    %></li>				
				<% elsif (params[:action] == 'show' )%>
				<li><h3><%= link_to 'SLOG', root_path %></h3> </li> 
				<li><%= link_to 'Back to View All Hikes', :controller => :hikes, :action => :index   %></li> 
				<% else %>
				<li><h3><%= link_to 'SLOG', root_path %></h3> </li> 
			<% end %>			
		</ul>
		<ul id="page-nav">
			<% if current_user %>
				Logged in as: <%= current_user.username %> |
       			<%= link_to "Log Out", session_path("current"), method: "delete" %> 
			<% else %>
			   <%= link_to 'Log In', new_session_path %>
			<% end %>
		</ul>
	</div>

	<div id="login-background">
	<!-- age specific starts here -->
	<%= yield %>
	</div>

</div> <!--wrapper-->

<div id="footer">
	
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= favicon_link_tag 'SLOGo.png'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag	 'welcome.scss' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	 

<div id="wrapper">

	<!-- age specific starts here -->
	<%= yield %>

</div> <!--wrapper-->

</body>
</html>

app/views/layouts/login-signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= favicon_link_tag 'SLOGo.png'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag	 'welcome.scss' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	<div id="main-nav">
		<ul>
			<li><%= image_tag("SLOGo.png") %></li>
			<li><h3><%= link_to 'SLOG', root_path %></h3> </li>
		</ul>
	</div>
	<div id="login-background">
	<!-- page specific starts here -->
	<%= yield %>
	</div>	
</div> <!--wrapper-->

<div id="footer">

</div>

</body>
</html>